runtime: python38
env: standard
instance_class: F1
automatic_scaling:
        max_instances: 1

handlers:
- url: /cert/
  static_files: content/index.html
  upload: content/index.html
- url: /cert
  static_dir: content
